app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/***************************************************************************************************
 * Authentication
 ***************************************************************************************************/
Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

/***************************************************************************************************
 * non authenticated - guests routes
 ***************************************************************************************************/
Route::get('/',['as'=>'home','uses'=>'HomeController@index']);
Route::get('/home',['as'=>'home','uses'=>'HomeController@index']);
Route::get('page/{id}',['as'=>'page','uses'=>'HomeController@show']);


/***************************************************************************************************
 * Admin Routes
 ***************************************************************************************************/
Route::group(['middleware'=>'admin.zone'], function () {


    Route::group(['namespace' => 'Admin'],function () {


        Route::resource('adminzone','DashBoardController');

    });

});


/***************************************************************************************************
 * Lessons learnt
 ***************************************************************************************************/

app/Http/Controllers/Admin/DashBoardController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Jobs\CreateImage;
use App\Src\Page\PageRepository;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class DashBoardController extends Controller
{

    public $pageRepository;

    public function  __construct(PageRepository $pageRepository)
    {

        $this->pageRepository = $pageRepository;

    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $allPages = $this->pageRepository->model->paginate(8);

        return view('backend.modules.page.index', ['allPages' => $allPages]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('backend.modules.page.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request $request
     * @return Response
     */
    public function store(Requests\CreatePage $request)
    {
        $pageCreated = $this->pageRepository->model->create(

            $request->except('_token', 'image_first', 'image_second')

        );

        $imagesCreated = $this->dispatch(new CreateImage($pageCreated, $request));

        if ($pageCreated) {

            return redirect()->back()->with(['success' => 'success-page-created']);
        }

        return redirect()->back()->with(['error' => 'error-page-created']);


    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        $page = $this->pageRepository->findWhereId($id);
        return view('backend.modules.page.edit', ['page' => $page]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request $request
     * @param  int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {

        if (!$request->hasFile('image_first')) {

            $request->except('image_first');

        }
        if (!$request->hasFile('image_second')) {

            $request->except('image_second');

        }
        $page = $this->pageRepository->findWhereId($id);

        // update the book table
        $page->fill($request->except('_token', '_method', 'pageId'));

        $hasBodyChanged = $page->isDirty('body') ? true : false;

        try {

            $page->update($request->except('_token', '_method', 'pageId'));

        } catch (\Exception $e) {

            return redirect()->back()->with('error', trans('word.error-update'));
        }

        $this->dispatch(new CreateImage($page,$request));

        return redirect()->back()->with('success', trans('word.success-update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        if ($id === 1) {
            return redirect()->back()->with('error', trans('word.error-delete'));
        } elseif ($this->pageRepository->findWhereId($id)->delete()) {

            return redirect()->back()->with('success', trans('word.success-delete'));
        }
        return redirect()->back()->with('error', trans('word.error-delete'));

    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;

abstract class Controller extends BaseController
{
    use DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Src\Page\PageRepository;
use Illuminate\Http\Request;
use App\Http\Requests;


class HomeController extends Controller
{
    public $pageRepository;

    public function __construct(PageRepository $pageRepository) {

        $this->pageRepository = $pageRepository;

    }
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {

        $pageIndex = $this->pageRepository->model->first();

        return view('frontend.pages.template',['page'=>$pageIndex]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $pageIndex = $this->pageRepository->findWhereId($id);

        return view('frontend.pages.template',['page'=>$pageIndex]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/layouts/_one_col.blade.php
@extends('frontend.layouts.master')


@section('container')

    <div class="row">

        @yield('content')

    </div>

@endsection

resources/views/backend/layouts/master.blade.php
<!doctype html>
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="nl"><![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8" lang="nl"><![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9" lang="nl"><![endif]-->
<!--[if IE]>
<html class="no-js ie" lang="nl"><![endif]-->
<!--[if !IE]><!-->
<html class="no-js" lang="nl"><!--<![endif]-->

<head>

    <meta charset="utf-8">
    <title>@yield(strip_tags('title'),'Graduation Project')</title>
    <meta name="description" content="My Graduation Project">
    <meta name="author" content="MEME">
    <meta name="viewport" content="width=device-width">
    <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon"/>

    @section('styles')
        @include('backend.styles.styles')
    @show

</head>

<body>

@include('backend.partials.nav')

<div class="container">

    <div class="content">


    @include('backend.partials.notifications')

    @section('container')
    @show

    </div>
</div>

@section('scripts')
    @include('backend.scripts.scripts')
@show


</body>


</html>

resources/views/backend/modules/page/create.blade.php
@extends('frontend.layouts._one_col')



@section('scripts')
    @parent
    {{--<script src="/css/bower_components/tinymce/tinymce.min.js"></script>
    <script src="/css/bower_components/tinymce/tinymce.jquery.min.js"></script>
    <script src="/css/bower_components/tinymce/plugins/template/plugin.min.js"></script>
    <script type="text/javascript">
        tinymce.init({
            selector: "textarea.editor",
            plugins: [
                ["advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker"],
                ["searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking"],
                ["save table contextmenu directionality emoticons template paste textcolor  directionality jbimages"]
            ],
            toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image jbimages | print preview media fullpage | forecolor backcolor emoticons | ltr rtl ",
            relative_urls: true
        });
    </script>--}}
@stop



@section('content')

    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-lg-6">
                    <h3>{{ trans('word.book-create') }}</h3>
                </div>
                <div class="col-lg-6">
                    <p style="color:red;">(*) - {{ trans('word.fields-required') }}</p>

                    <p style="color:red;">(*) - {{ trans('word.cover-instructions') }}</p>
                </div>
            </div>
        </div>
        <div class="panel-body">
            {!! Form::open(['route' => 'adminzone.store', 'method' => 'post','files'=>'true'],
            ['class'=>'form-horizontal']) !!}
            <div class="row">
                <div class="form-group col-md-3 col-lg-3">
                    {!! Form::label('image_first', trans('word.image') , ['class' => 'control-label']) !!}*
                    {!! Form::file('image_first', ['class' => 'form-control']) !!}
                </div>
                <div class="form-group col-md-3 col-lg-3">
                    {!! Form::label('image_second', trans('word.image') , ['class' => 'control-label']) !!}*
                    {!! Form::file('image_second',['class' => 'form-control' ]) !!}
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-4 col-lg-4">
                    {!! Form::label('title', trans('word.page-title'), ['class' => 'control-label']) !!}*
                    {!! Form::text('title', null, ['class' => 'form-control']) !!}
                </div>

                <div class="form-group col-md-4 col-lg-4">
                    {!! Form::label('header', trans('word.title'), ['class' => 'control-label']) !!}*
                    {!! Form::text('header', null, ['class' => 'form-control']) !!}
                </div>

            </div>
            <div class="form-group">
                {!! Form::label('body', trans('word.content'), ['class' => 'control-label']) !!}*
                {!! Form::textarea('body', null, ['class' => 'form-control editor']) !!}
            </div>

            <div class="form-group">
                <div class="col-lg-6">
                    {!! Form::submit(trans('word.save'), ['class' => 'btn btn-primary form-control']) !!}
                </div>
                <div class="col-lg-6">
                    <a class="btn btn-danger form-control" href="{{ URL::previous() }}">{{ trans('word.cancel') }}</a>
                </div>
            </div>
        </div>
    </div>


    {!! Form::close() !!}

@endsection

resources/views/backend/modules/page/edit.blade.php
@extends('frontend.layouts._one_col')



@section('scripts')
    @parent
    {{--<script src="/css/bower_components/tinymce/tinymce.min.js"></script>
    <script src="/css/bower_components/tinymce/tinymce.jquery.min.js"></script>
    <script src="/css/bower_components/tinymce/plugins/template/plugin.min.js"></script>
    <script type="text/javascript">
        tinymce.init({
            selector: "textarea.editor",
            plugins: [
                ["advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker"],
                ["searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking"],
                ["save table contextmenu directionality emoticons template paste textcolor  directionality jbimages"]
            ],
            toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image jbimages | print preview media fullpage | forecolor backcolor emoticons | ltr rtl ",
            relative_urls: true
        });
    </script>--}}
@stop



@section('content')

    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-lg-6">
                    <h3>{{ trans('word.book-create') }}</h3>
                </div>
                <div class="col-lg-6">
                    <p style="color:red;">(*) - {{ trans('word.fields-required') }}</p>

                    <p style="color:red;">(*) - {{ trans('word.cover-instructions') }}</p>
                </div>
            </div>
        </div>
        <div class="panel-body">
            {!! Form::model($page,['route' => ['adminzone.update',$page->id], 'method' => 'PATCH','files'=>'true'],
            ['class'=>'form-horizontal']) !!}
            {!! Form::hidden('pageId',$page->id) !!}
            <div class="row">
                <div class="col-lg-3 col-lg-offset-3">
                    <img class="img-thumbnail img-responsive" src="/img/pages/thumbnail/{{$page->image_first}}" alt=""/>
                </div>
                <div class="col-lg-3">
                    <img class="img-thumbnail img-responsive" src="/img/pages/thumbnail/{{$page->image_second}}"
                         alt=""/>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-3 col-lg-3">
                    {!! Form::label('image_first', trans('word.image') , ['class' => 'control-label']) !!}*
                    {!! Form::file('image_first', ['class' => 'form-control','placeholder'=> trans('word.image') ]) !!}
                </div>
                <div class="form-group col-md-3 col-lg-3">
                    {!! Form::label('image_second', trans('word.image') , ['class' => 'control-label']) !!}*
                    {!! Form::file('image_second',['class' => 'form-control','placeholder'=> trans('word.image') ]) !!}
                </div>
            </div>
            <div class="row" style="padding: 10px;">
                <div class="form-group col-md-4 col-lg-4">
                    {!! Form::label('title', trans('word.page-title'), ['class' => 'control-label']) !!}*
                    {!! Form::text('title', $page->title, ['class' => 'form-control']) !!}
                </div>
                <div class="col-lg-1"></div>
                <div class="form-group col-md-4 col-lg-4">
                    {!! Form::label('header', trans('word.title'), ['class' => 'control-label']) !!}*
                    {!! Form::text('header', $page->header, ['class' => 'form-control']) !!}
                </div>
            </div>

            <div class="form-group">
                {!! Form::label('body', trans('word.content'), ['class' => 'control-label']) !!}*
                {!! Form::textarea('body', $page->body, ['class' => 'form-control editor']) !!}
            </div>

            <div class="form-group">
                <div class="col-lg-6">
                    {!! Form::submit(trans('word.save'), ['class' => 'btn btn-primary form-control']) !!}
                </div>
                <div class="col-lg-6">
                    <a class="btn btn-danger form-control" href="{{ URL::previous() }}">{{ trans('word.cancel') }}</a>
                </div>
            </div>
        </div>
    </div>


    {!! Form::close() !!}

@endsection

resources/views/backend/modules/page/index.blade.php
@extends('backend.layouts._one_col')

@section('content')
    <div class="row">
        <div class="col-xs-12">

            <!-- START CONTENT ITEM -->
            <ul class="nav nav-tabs">
                <li id="tab-1" class="active" href="#step1"><a class="active" href="#step1" data-toggle="tab"><i
                                class="fa fa-aw fa-book"></i>&nbsp;{{ trans('word.pages') }} </a></li>
            </ul>

            {{--All Books--}}

            <div class="tab-content">

                <div class="tab-pane active" id="step1">
                    <div class="row">
                        <div class="col-xs-12 paddingTop10">
                            @if($allPages->count() > 0)
                                <table class="table table-striped table-order" id="booksTable">
                                    <thead>
                                    <tr style="background-color:#E0E0E0; text-align: center;">
                                        <th class="hidden-xs">{{ trans('word.id') }}</th>
                                        <th>{{ trans('word.title') }}</th>
                                        <th>{{ trans('word.header') }}</th>
                                        <th>{{ trans('word.body') }}</th>
                                        <th>{{ trans('word.created-at') }}</th>
                                        <th>{{ trans('word.edit') }}</th>
                                        <th>{{ trans('word.remove') }}</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($allPages as $page)
                                        <tr>
                                            <td class="hidden-xs">{{ $page->id }}</td>
                                            <td>
                                                <a href="{{ action('HomeController@show', $page->id) }}"> {!!
                                                    $page->title
                                                    !!} </a>


                                            </td>
                                            <td>
                                                <p> {!! Str::words(strip_tags($page->header),4) !!} </p>

                                            </td>
                                            <td>
                                                <p> {!! Str::words(strip_tags($page->body),4) !!} </p>
                                            </td>
                                            <td>
                                                <span> {{ $page->created_at->format('Y-m-d') }} </span>
                                            </td>
                                            <td class="text-left">
                                                <a class="btn btn-sm btn-info text-center" href="{{ route('adminzone.edit',$page->id) }}"><i class="fa fa-edit fa-fw"></i></a>
                                            </td>
                                            <td class="text-left">
                                                <button type="button" class="btn btn-danger btn-xs" data-toggle="modal"
                                                        data-target="#myModal-{{$page->id}}" href="">
                                                    <i class="fa fa-trash-o fa-2x"></i>
                                                </button>
                                                @include('backend.partials._delete_modal')
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            @else
                                <div class="alert alert-warning"
                                     role="alert">{{ trans('word.no-pages-found') }}</div>
                            @endif
                        </div>
                        {!! $allPages->render() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/backend/partials/_delete_modal.blade.php
<div class="modal" id="myModal-{{$page->id}}">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><i class="fa fa-lg fa-warning"></i> {!! trans('word.delete') !!}</h4>
            </div>
            <div class="modal-body">
                <p>{!! trans('word.are-u-sure') !!}</p>
            </div>
            <div class="modal-footer">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-lg-offset-3 col-md-offset-3">
                        <div class="col-lg-6">
                            <button type="button" class="btn btn-success" data-dismiss="modal">{!! trans('word.close') !!}</button>
                        </div>
                        <div class="col-lg-6">
                            {!! Form::open(['action' => ['Admin\DashBoardController@destroy',$page->id],'method'=>'DELETE'],['class'=>'form-horizontal']) !!}
                            <div class="form-group">
                                <button type="submit" class="btn btn-danger">{!! trans('word.delete') !!}</button>
                            </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>

            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

resources/views/backend/partials/nav.blade.php
<nav class="navbar navbar-inverse navbar-fixed-top col-lg-12">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ route('home') }}">Home</a></li>
                @if(count($menu) > 0)
                    @foreach($menu as $menu)
                        <li><a href="{{ route('page',$menu->id) }}">{{$menu->title}}</a></li>
                    @endforeach
                @endif
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Control Panel <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        @if(Auth::user())
                        <li><a href="#" class="text-warning">Logged in as {{ Auth::user()->name }}</a></li>
                            @if(Auth::user()->getCurrentUserRole())
                                <li role="separator" class="divider"></li>
                                <li class="text-danger"><a href="{{ route('adminzone.index') }}"><i class="fa fa-user fa-aw"></i>  DashBoard </a></li>
                            <li role="separator" class="divider"></li>
                            <li class="text-danger"><a href="{{ route('adminzone.create') }}"><i class="fa fa-pencil-square fa-aw"></i> Create New Page</a></li>
                            @endif
                        <li role="separator" class="divider"></li>
                        <li class="bg-danger"><a href="/auth/logout"><i class="fa fa-fw fa-circle-o"></i>Log out</a></li>
                        @else
                        <li><a href="/auth/login" class="text-warning"><i class="fa fa-fw fa-sign-out"></i>Log in</a></li>
                        <li><a href="/auth/register" class="text-warning">Regsiter</a></li>
                        @endif
                    </ul>
                </li>
            </ul>

        </div>
        <!--/.nav-collapse -->
    </div>
</nav>

resources/views/backend/partials/notifications.blade.php
<div class="row">

    @if ($message = Session::get('success'))
        <div class="alert alert-success alert-block">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            @if(is_array($message))
                @foreach ($message as $m)
                    {{ $m }}
                @endforeach
            @else
                {{ $message }}
            @endif
        </div>
    @endif

    @if ($message = Session::get('error'))
        <div class="alert alert-danger alert-block">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            @if(is_array($message))
                @foreach ($message as $m)
                    {{ $m }}
                @endforeach
            @else
                {{ $message }}
            @endif
        </div>
    @endif

    @if ($message = Session::get('errors'))
        <div class="alert alert-danger alert-block">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            @if($message->all())
                @foreach ($message->all() as $m)
                    <li>{{ $m }}  </li>
                @endforeach
            @endif
        </div>
    @endif

    @if ($message = Session::get('warning'))
        <div class="alert alert-warning alert-block">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            @if(is_array($message))
                @foreach ($message as $m)
                    {{ $m }}
                @endforeach
            @else
                {{ $message }}
            @endif
        </div>
    @endif

    @if ($message = Session::get('info'))
        <div class="alert alert-info alert-block">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            @if(is_array($message))
                @foreach ($message as $m)
                    {{ $m }}
                @endforeach
            @else
                {{ $message }}
            @endif
        </div>

</div>
@endif

resources/views/backend/scripts/scripts.blade.php
    <script src="{{ asset('js/app.js') }}"></script>

resources/views/backend/styles/styles.blade.php
    <link rel="stylesheet" href="{{asset('css/app.css')}}"/>
    <link rel="stylesheet" href="{{ asset('css/custom.css') }}"/>

resources/views/frontend/layouts/_one_col.blade.php
@extends('frontend.layouts.master')


@section('container')

    <div class="row">

        @yield('content')

    </div>

@endsection

resources/views/frontend/partials/nav.blade.php
<nav class="navbar navbar-inverse navbar-fixed-top col-lg-12">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ route('home') }}">Home</a></li>
                @if(count($menu) > 0  && $menu != 'menu')
                    @foreach($menu as $menu)
                        <li><a href="{{ route('page',$menu->id) }}">{{$menu->title}}</a></li>
                    @endforeach
                @endif
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Control Panel <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        @if(Auth::user())
                        <li><a href="#" class="text-warning">Logged in as {{ Auth::user()->name }}</a></li>
                            @if(Auth::user()->getCurrentUserRole())
                                <li role="separator" class="divider"></li>
                                <li class="text-danger"><a href="{{ route('adminzone.index') }}"><i class="fa fa-user fa-aw"></i> DashBoard </a></li>
                            <li role="separator" class="divider"></li>
                            <li class="text-danger"><a href="{{ route('adminzone.create') }}"><i class="fa fa-pencil-square fa-aw"></i> Create New Page</a></li>
                            @endif
                        <li role="separator" class="divider"></li>
                        <li class="bg-danger"><a href="/auth/logout"><i class="fa fa-fw fa-sign-out"></i>Log out</a></li>
                        @else
                        <li><a href="/auth/login" class="text-warning">Log in</a></li>
                        <li><a href="/auth/register" class="text-warning">Regsiter</a></li>
                        @endif
                    </ul>
                </li>
            </ul>

        </div>
        <!--/.nav-collapse -->
    </div>
</nav>

resources/views/frontend/scripts/scripts.blade.php
    <script src="{{ asset('js/app.js') }}"></script>

resources/views/frontend/styles/styles.blade.php
    <link rel="stylesheet" href="{{asset('css/app.css')}}"/>
    <link rel="stylesheet" href="{{ asset('css/custom.css') }}"/>